### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by kris-terziev** [GeneaLabs/Jumpstart#1]
[InvalidArgumentException]               
  Command "app:jumpstart" is not defined.  
  Did you mean this?                       
      app:name

**Comment by Djelibeybi** [comment]
Jumpstart needs to be manually added to `config/app.php`'s list of providers as `GeneaLabs\Jumpstart\JumpstartServiceProvider::class,`

**Comment by mikebronner** [comment]
Aw, sorry guys ... will add that to the docs. Completely forgot about it because its so routine :)

**Comment by mikebronner** [comment]
Added now, thanks for the assist, @Djelibeybi ! :)
