### ISSUE TITLE
Requires PHP 5.6 which is not available for OS X

### ISSUE THREAD

**Issue by Djelibeybi** [GeneaLabs/Jumpstart#2]
The composer.json requires PHP 5.6 but OS X only ships with PHP 5.5, so it can't be installed outside of a Homestead VM. Which means once it's installed, you can't run composer in OS X any more, only in the VM.

Is PHP 5.6 absolutely necessary for Jumpstart? Laravel itself only requires PHP >= 5.5.9.

**Comment by mikebronner** [comment]
Will fix ... didn't realize the ramifications.

**Comment by Djelibeybi** [comment]
:+1:

**Comment by mikebronner** [comment]
Update should be available in composer at any moment.
